"""Add unique constraint for input_label_id + difficulty

Revision ID: 32be1515b80d
Revises: 8f38815df318
Create Date: 2025-09-22 16:03:44.823334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32be1515b80d'
down_revision = '8f38815df318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refined_labels', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_label_difficulty', ['input_label_id', 'difficulty'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refined_labels', schema=None) as batch_op:
        batch_op.drop_constraint('uq_label_difficulty', type_='unique')

    # ### end Alembic commands ###
