"""Add index to token_blocklist jti column

Revision ID: 8f38815df318
Revises: af89903e57cc
Create Date: 2025-06-10 17:11:08.477897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f38815df318'
down_revision = 'af89903e57cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('token_blocklist_jti_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))
        batch_op.create_unique_constraint(batch_op.f('token_blocklist_jti_key'), ['jti'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
