from db import db

# Gemini output based on label
class RefinedLabelModel(db.Model):
    __tablename__ = "refined_labels"

    id = db.Column(db.Integer, primary_key=True)
    # Text generated by Gemini based on label
    generated_text = db.Column(db.Text, nullable=False)
    # Store the difficulty level desired by user / viewer
    # Options: "simple", "intermediate", "in_depth"
    difficulty = db.Column(db.String(20), nullable = False)
    # Relationships to original label
    input_label_id = db.Column(db.Integer, db.ForeignKey("labels.id"), nullable = False)
    # Matches "refined_label" in LabelModel
    input_label = db.relationship("LabelModel", back_populates = "refinements")